name: SelimCore
main: selim.core.SelimCore
depend: [ProtocolLib]
version: 1.2.0
commands:
  viewrecipe:
    description: View recipes registered with SelimCore and most vanilla recipes.
    usage: /viewrecipe <name> [num]
  pluginversion:
    description: Gets the installed version of the given plugin.
    usage: /pluginversion <pluginName>