name: SelimCore
main: selim.core.SelimCore
depend: [ProtocolLib]
version: 1.3.0
commands:
  viewrecipe:
    description: View recipes registered with SelimCore and most vanilla recipes.
    usage: /viewrecipe <name> [num]
  pluginversion:
    description: Gets the installed version of the given plugin.
    usage: /pluginversion <pluginName>
  setupscoreboard:
    description: Sets up a display scoreboard for supported plugins.
    usage: /setupscoreboard <scoreboardID> <x> <y> <z> <face> <place>
  setupgamesign:
    description: Sets up a display game sign for supported plugins.
    usage: /setupgamesign <gameID> <x> <y> <z> <face>